### ISSUE TITLE
License For this LIB

### ISSUE THREAD

**Issue by theNerd247** [theNerd247/JavaCSVReader#13]
I realized the other day that this code has yet to be brought under license. As seen the master branch contains no deployable code yet I think we should let this slide for now. However the FIRST merge to the master branch must contain an open source license. 

PS: I suggest GNU Public License.

**Comment by slix** [comment]
I assume that there will be a Java API for robot code to use JavaCSVReader, right?

If so, using the GPL would mean any code using JavaCSVReader would need to be licensed under the GPL (if the code or application is distributed). That means any team using JavaCSVReader that wants to release their code would have to release it under the GPL.

**Comment by theNerd247** [comment]
Yes, the JavaCSVReader is going to eventually contain code to use for the robot.

Would are there any better options for licensing? Possibly we wont need any license?

**Comment by slix** [comment]
Most open-source software projects need some sort of license. A license gives permission for other people to modify and use your code (possibly with certain restrictions). Otherwise, it's technically theft.

I don't think the GPL is a good idea because this project and FRC teams don't need its protections against proprietary software.

WPILib uses the [BSD license](http://www.opensource.org/licenses/bsd-license.php). That's a simple, permissive license that essentially says "do whatever you want with this code." That's probably a good choice.

If you really want a copyleft license without forcing teams to use the GPL license if they release their robot code, look at the LGPL.

Licensing is pretty complicated. For more information, see the [Getting Started](http://producingoss.com/en/license-quickstart.html) and [Choosing a License](http://producingoss.com/en/license-choosing.html) sections of Producing Open Source Software by Karl Fogel. Also see [What is Copyleft?](http://www.gnu.org/copyleft/copyleft.html)

**Comment by theNerd247** [comment]
I think BSD is what we should go with in that case. It's simple and fits with the WPILib. I'll add it to the next merge to master. 

@Slix: do you have a lot of experience in licenses? If so would you mind forking the project and help adding it in? I've never done this before.

**Comment by slix** [comment]
I just do a lot of reading. :P

Sure! It's not very involved. I'll submit a pull request later today or tomorrow.
